baseURL = 'https://chipsalliance.github.io/chips-alliance-website'
languageCode = 'en-us'
title = 'CHIPS Alliance'


[module]
replacements = "local/component-library -> ../component-library"

[[module.imports]]
path = 'local/component-library'

[[module.imports]]
path = 'github.com/cloudcannon/bookshop/hugo/v3'
