# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive  # Fetch the Docsy theme
          fetch-depth: 0         # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          # The action defaults to search for the dependency file (package-lock.json,
          # npm-shrinkwrap.json or yarn.lock) in the repository root, and uses its
          # hash as a part of the cache key.
          # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data
          cache-dependency-path: '**/package-lock.json'

      - name: Get PR metadata
        uses: 8BitJonny/gh-get-current-pr@2.2.0
        if: github.event_name == 'pull_request'
        with:
          sha: ${{ github.event.pull_request.head.sha }}
        id: PR

      - run: npm ci
      - run: hugo --minify --baseURL https://${{ github.repository_owner }}.github.io/$( echo ${{ github.repository }} | cut -d/ -f 2)/
        if: ${{ github.ref == 'refs/heads/main' }}
      - run: hugo --minify --baseURL https://${{ github.repository_owner }}.github.io/$( echo ${{ github.repository }} | cut -d/ -f 2)/preview/${{ steps.PR.outputs.number }}/
        if: github.event_name == 'pull_request'
      - run: cp -a static public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      # prepare metadata and upload artifacts for multi branch deployment
      - name: Move deployment to the correct preview directory
        if: github.event_name == 'pull_request'
        run: |
          mkdir preview/
          mv ./public preview/${{ steps.PR.outputs.number}}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: github.event_name == 'pull_request'
        with:
          name: pr_deployment
          path: ./preview/
